Refactor new script to be more posix compliant
Type: refactor

diff --git a/new/helpers b/new/helpers
--- a/new/helpers
+++ b/new/helpers
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 # Display usage message.
-function usage()
+usage()
 {
     printf "%b"                                                                \
     "Create default templates for files.\n\n"                                  \
                                                                                \
     "Usage:\n"                                                                 \
-    "  new [options] <filename>...\n\n"                                        \
+    "  new [option]... <filename>...\n\n"                                      \
                                                                                \
     "Arguments:\n"                                                             \
     "  filename           name of the file to create.\n\n"                     \
@@ -27,40 +27,44 @@ function usage()
     "                     editing in vim.\n"
 }
 
-# Returns 0 if $1 makefile type is in $MAKEFILE_TYPES
-function makefile_supported()
+# Returns 0 if $1 makefile type is in $MAKEFILE_TYPES.
+makefile_supported()
 {
-    local type=$1
+    local type="$1"
 
     for make_type in "${MAKEFILE_TYPES[@]}"; do
-        if [[ "$make_type" == "$type" ]]; then
+        if [ "${make_type}" = "${type}" ]; then
             return 0
         fi
     done
+
     return 1
 }
 
 # Copy $1 template from templates directory into $2 file.
-function copy_template()
+copy_template()
 {
-    local template="$TEMPLATES_DIR/$1"
-    local filename=$2
+    local template="${TEMPLATES}/$1"
+    local filename="$2"
 
     # if filename doesn't exist in pwd
-    if [[ ! -f "$(pwd)/$filename" ]]; then
+    if [ ! -f "$(pwd)/${filename}" ]; then
         # if template doesn't exist
-        if [[ ! -f "$template" ]]; then
-            echo "$SCRIPT_NAME: template not found '$template'" >&2
+        if [ ! -f "${template}" ]; then
+            echo "${SCRIPT}: template not found '${template}'" >&2
         else
-            cp "$template" "$filename"
+            cp "${template}" "${filename}"
         fi
     else
-        if [[ ${FLAGS[force]} -eq 1 ]]; then
-            cp "$template" "$filename"
+        if [ "${FLAGS[force]}" = 'true' ]; then
+            cp "${template}" "${filename}"
         else
-            echo "$SCRIPT_NAME: file '$filename' already exists"
-            read -rep 'Rewrite ? [y/n]: ' ans
-            [[ "$ans" =~ ^[yY]$ ]] && cp "$template" "$filename"
+            printf "%b" \
+            "${SCRIPT}: file '${filename}' already exists\nRewrite? [y/n]: "
+            read -r ans
+            if [ "${ans}" = 'y' ] || [ "${ans}" = 'Y' ]; then
+                cp "${template}" "${filename}"
+            fi
         fi
     fi
 }
diff --git a/new/settings b/new/settings
--- a/new/settings
+++ b/new/settings
@@ -1,57 +1,51 @@
 #!/bin/bash
 
 # Absolute import
-. $(dirname $(realpath $0))/helpers.sh
+. "$(dirname "$(realpath "$0")")"/helpers
 
-SCRIPT_NAME='new'  # used in error messages
-
+SCRIPT='new'  # used in error messages
 SHORT_OPTS='efm:'
 LONG_OPTS='edit,force,help,make:'
-HELP="Try '$SCRIPT_NAME --help' for more information."
+HELP="Try '${SCRIPT} --help' for more information."
 
 # Default templates must be in this directory.
-TEMPLATES_DIR="$(dirname $(realpath $0))/templates"
-
+TEMPLATES="$(dirname "$(realpath "$0")")/templates"
 MAKEFILE_NAME='Makefile'
-MAKEFILE_TYPES=(c-project c-shared cpp-project)
+MAKEFILE_TYPES=('c-project' 'c-shared' 'cpp-project')
 
-# Each flag is either ON (1) or OFF (0).
+# Each flag is either ON (true) or OFF (false).
 declare -A FLAGS=(
-    [edit]=0    # -e, --edit
-    [force]=0   # -f, --force
+    [edit]='false'   # -e, --edit
+    [force]='false'  # -f, --force
 )
 
 # Each option has a string argument.
 declare -A OPTS=(
-    [make]=''   # -m, --make
+    [make]=''        # -m, --make
 )
 
 # Line numbers where cursor should appear if --edit flag is on.
 declare -A CURSOR_LINE_NUMBERS=(
-    [c]=5
-    [cpp]=8
+    [c]=6
+    [cpp]=10
     [html]=12
-    [py]=6
+    [py]=7
 )
 
-ARGV=$(getopt -o $SHORT_OPTS -l $LONG_OPTS -- "$@")
-
-# If error during parsing in getopt appeared.
-if [[ $? -ne 0 ]]; then
-    echo "$HELP" >&2
+# If getopt cound't parse options:
+if ! ARGV=$(getopt -o ${SHORT_OPTS} -l ${LONG_OPTS} -- "$@"); then
+    echo "${HELP}" >&2
     exit 1
 fi
 
-eval set -- "$ARGV"
+eval set -- "${ARGV}"
 
 while true; do
     case $1 in
         -e | --edit)
-            FLAGS[edit]=1
-            ;;
+            FLAGS[edit]='true' ;;
         -f | --force)
-            FLAGS[force]=1
-            ;;
+            FLAGS[force]='true' ;;
         --help)
             usage
             exit 0
@@ -59,10 +53,10 @@ while true; do
         -m | --make)
             shift
             if ! makefile_supported "$1"; then
-                echo "$SCRIPT_NAME: invalid argument '$1' for '--make'" >&2
+                echo "${SCRIPT}: invalid argument '$1' for '--make'" >&2
                 echo 'Valid arguments are:'
                 printf "  - '%s'\n" "${MAKEFILE_TYPES[@]}"
-                echo "$HELP" >&2
+                echo "${HELP}" >&2
                 exit 1
             fi
             OPTS[make]="$1"
